#!/usr/bin/env python3
"""Generate pairwise Robot test suites from `tools/params.json` and `tests/template_case.robot`.

Usage: python tools/generate_pairwise.py [--limit N]

If `allpairspy` is available it will be used for pairwise generation; otherwise a sampled
cartesian product is used (limited to `--limit`, default 250).
"""
from __future__ import annotations
import json
import os
import sys
import itertools
from datetime import date, timedelta

try:
    from allpairspy import AllPairs
    HAVE_ALLPAIRS = True
except Exception:
    HAVE_ALLPAIRS = False


ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
PARAMS_PATH = os.path.join(ROOT, 'tools', 'params.json')
TEMPLATE_PATH = os.path.join(ROOT, 'robotFrameworkTests', 'tests', 'template_case.robot')
OUT_DIR = os.path.join(ROOT, 'robotFrameworkTests', 'tests', 'generated')


def load_params():
    with open(PARAMS_PATH, 'r', encoding='utf-8') as f:
        return json.load(f)


def normalize(v):
    # represent None/empty as empty string
    if v is None:
        return ''
    return str(v)


def expand_ard(token: str) -> str:
    today = date.today()
    if token == '' or token is None:
        return ''
    if token == 'VALID_RECENT':
        return (today - timedelta(days=90)).isoformat()
    if token == 'FUTURE':
        return (today + timedelta(days=1)).isoformat()
    if token == 'INVALID_OLD':
        return (today - timedelta(days=400)).isoformat()
    return token


def make_values_list(params):
    keys = [
        ('browsers', 'BROWSER'),
        ('noteType', 'NOTE_TYPE'),
        ('residentName', 'RESIDENT_NAME'),
        ('dpoa', 'DPOA'),
        ('ages', 'AGE'),
        ('ard', 'ARD'),
        ('orientation', 'ORIENTATION'),
        ('bims', 'BIMS'),
        ('phq', 'PHQ'),
        ('behavior', 'BEHAVIOR'),
        ('careConference', 'CARE_CONFERENCE'),
        ('polst', 'POLST'),
    ]
    lists = []
    varnames = []
    for pkey, vname in keys:
        vals = params.get(pkey, [''])
        # convert all to strings and expand ARD special tokens lazily
        if pkey == 'ard':
            vals = [expand_ard(v) for v in vals]
        else:
            vals = [normalize(v) for v in vals]
        lists.append(vals)
        varnames.append(vname)
    return varnames, lists


def generate_pairs(varnames, lists, limit=250):
    if HAVE_ALLPAIRS:
        print('Using allpairspy for pairwise generation')
        pairs = list(AllPairs(lists))
        return [tuple(map(str, p)) for p in pairs]
    # fallback: sample cartesian product up to limit
    print('allpairspy not available — using sampled cartesian product (fallback)')
    prod = itertools.product(*lists)
    combos = []
    for i, c in enumerate(prod):
        if i >= limit:
            break
        combos.append(tuple(map(str, c)))
    return combos


def render_variables_block(varnames, values):
    lines = ['*** Variables ***']
    # include common app variables so generated files are self-contained
    # Generated files live in tests/generated, so go two levels up to repo root
    # After moving Robot tests under robotFrameworkTests/tests, generated files
    # live in robotFrameworkTests/tests/generated so go three levels up to repo root
    lines.append("${APP_URL}    file://${CURDIR}/../../../MDS_html.html")
    lines.append("${SCREENSHOT_DIR}    ${CURDIR}/../../../results_full/screenshots")
    for name, val in zip(varnames, values):
        # ensure Robot variable syntax and preserve blank values
        lines.append(f'${{{name}}}    {val}')
    return '\n'.join(lines) + '\n\n'


def load_template():
    with open(TEMPLATE_PATH, 'r', encoding='utf-8') as f:
        return f.read()


def write_generated(template, variables_block, out_path, index, vector):
    header = f'# Generated by tools/generate_pairwise.py\n# vector: {vector}\n\n'
    # Replace the Variables section in the template; if not found, prepend
    if '*** Variables ***' in template and '*** Test Cases ***' in template:
        pre, rest = template.split('*** Variables ***', 1)
        # rest starts with variables content; find Test Cases marker
        if '*** Test Cases ***' in rest:
            _vars, post = rest.split('*** Test Cases ***', 1)
            new_content = pre + variables_block + '*** Test Cases ***' + post
        else:
            new_content = header + variables_block + template
    else:
        new_content = header + variables_block + template

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(new_content)


def ensure_out_dir():
    os.makedirs(OUT_DIR, exist_ok=True)


def main(argv):
    limit = 250
    if '--limit' in argv:
        try:
            limit = int(argv[argv.index('--limit') + 1])
        except Exception:
            pass
    params = load_params()
    varnames, lists = make_values_list(params)
    combos = generate_pairs(varnames, lists, limit=limit)
    template = load_template()
    ensure_out_dir()
    # clean old generated files
    for fn in os.listdir(OUT_DIR):
        if fn.endswith('.robot'):
            try:
                os.remove(os.path.join(OUT_DIR, fn))
            except Exception:
                pass

    for i, vec in enumerate(combos, start=1):
        vars_block = render_variables_block(varnames, vec)
        out_path = os.path.join(OUT_DIR, f'case_{i:04d}.robot')
        write_generated(template, vars_block, out_path, i, vec)

    print(f'Wrote {len(combos)} generated suites to {OUT_DIR}')


if __name__ == '__main__':
    main(sys.argv)
